[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{ access = "write", path = "./reports" }]
libraries=[
    "src/contracts/protocol/libraries/logic/ReserveLogic.sol:ReserveLogic:0xe58575ba47a348e3c2f9b7ec3eccfbb189ccc6ec",
    "src/contracts/protocol/libraries/logic/GenericLogic.sol:GenericLogic:0xeae736e5d6560169f9285c62492f8a89fb4ab790",
    "src/contracts/protocol/libraries/logic/ValidationLogic.sol:ValidationLogic:0xb65308a8F4cE57a72F13312CeCBaAf47601A574A"
]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
zkevm = "${RPC_ZKEVM}"
gnosis = "${RPC_GNOSIS}"
bnb = "${RPC_BNB}"

[etherscan]
mainnet = { key="${ETHERSCAN_API_KEY_MAINNET}", chainId=1 }
optimism = { key="${ETHERSCAN_API_KEY_OPTIMISM}", chainId=10 }
avalanche = { key="${ETHERSCAN_API_KEY_AVALANCHE}", chainId=43114 }
polygon = { key="${ETHERSCAN_API_KEY_POLYGON}", chainId=137 }
arbitrum = { key="${ETHERSCAN_API_KEY_ARBITRUM}", chainId=42161 }
fantom = { key="${ETHERSCAN_API_KEY_FANTOM}", chainId=250 }
metis = { key="any", chainId=1088, url='https://andromeda-explorer.metis.io/' }
base = { key="${ETHERSCAN_API_KEY_BASE}", chainId=8453 }
zkevm = { key="${ETHERSCAN_API_KEY_ZKEVM}", chainId=1101 }
gnosis = { key="${ETHERSCAN_API_KEY_GNOSIS}", chainId=100 }
bnb = { key="${ETHERSCAN_API_KEY_BNB}", chainId=56 }

# See more config options https://github.com/gakonst/foundry/tree/master/config
